name: techno_kitchen_dart
description: A library for interacting with the SDGB API.
version: 1.0.0-dev.1
repository: https://github.com/qianmo2233/techno_kitchen_dart
example:
  script: example/techno_kitchen_dart_example.dart
  description: Example usage of the Techno Kitchen Dart API client.
  main: example/techno_kitchen_dart_example.dart

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  encrypt: ^5.0.3
  archive: ^4.0.7
  crypto: ^3.0.6
  http: ^1.4.0
  intl: ^0.20.2
  timezone: ^0.10.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
